# all packages used:
name: fv
channels:
 - pytorch
 - huggingface
 - nvidia
 - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.7.0
  - datasets=2.14.3
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=1.5.3
  - plotly=5.9.0
  - pytorch=1.13.0
  - pip=23.2.1
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - sentencepiece=0.1.99
  - transformers=4.31.0
  - tqdm=4.65.0
  - pip:
    - git+https://github.com/davidbau/baukit@main#egg=baukit
    - bitsandbytes==0.41.1
    - huggingface-hub==0.16.4
    - accelerate==0.21.0